# This file was generated by GoReleaser. DO NOT EDIT.
cask "gh-attach" do
  name "gh-attach"
  desc "GitHub user attachment upload CLI for gh"
  homepage "https://github.com/sudosubin/gh-attach"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/sudosubin/gh-attach/releases/download/v#{version}/gh-attach-darwin-amd64"
      sha256 "eff2b26fe5cefea7b557812313fd6b55269bd90db33983bd5bbc5649f658e897"
      binary "gh-attach-darwin-amd64", target: "gh-attach"
    end
    on_arm do
      url "https://github.com/sudosubin/gh-attach/releases/download/v#{version}/gh-attach-darwin-arm64"
      sha256 "a1fd2ea82b762634cdb2dc89dc0a2dcdd85ff4080113eab506d718b238618dbd"
      binary "gh-attach-darwin-arm64", target: "gh-attach"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sudosubin/gh-attach/releases/download/v#{version}/gh-attach-linux-amd64"
      sha256 "aaed9e2b9a9add69ffa38ecd9c6aba38b1ef4f6694df2c1743c178d5d11b8805"
      binary "gh-attach-linux-amd64", target: "gh-attach"
    end
    on_arm do
      url "https://github.com/sudosubin/gh-attach/releases/download/v#{version}/gh-attach-linux-arm64"
      sha256 "b3a7c022639b296608419ae767f6eefe2890686422ec202eafed1965ecfed117"
      binary "gh-attach-linux-arm64", target: "gh-attach"
    end
  end

  # No zap stanza required
end
