# This file was generated by GoReleaser. DO NOT EDIT.
cask "gh-attach" do
  name "gh-attach"
  desc "GitHub user attachment upload CLI for gh"
  homepage "https://github.com/sudosubin/gh-attach"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gh-attach"

  on_macos do
    on_intel do
      url "https://github.com/sudosubin/gh-attach/releases/download/v#{version}/gh-attach_#{version}_darwin_amd64.tar.gz"
      sha256 "9c0d7a29ace7ada49334f1af73778f58e67be17ece26e6722922d94b7b60efe2"
    end
    on_arm do
      url "https://github.com/sudosubin/gh-attach/releases/download/v#{version}/gh-attach_#{version}_darwin_arm64.tar.gz"
      sha256 "31b21c6228f8b565196aecd5e2d5d581d9e3f2468ed15b5b9292d8c6c6813e8d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sudosubin/gh-attach/releases/download/v#{version}/gh-attach_#{version}_linux_amd64.tar.gz"
      sha256 "4f693a5f1b82b46ab549ecf8078b4d7aa2c862f4d50659b165d171f370728153"
    end
    on_arm do
      url "https://github.com/sudosubin/gh-attach/releases/download/v#{version}/gh-attach_#{version}_linux_arm64.tar.gz"
      sha256 "248b9243309b109657e5550d4a435d9dcf92e1da19a882f01cf42f618a9a9453"
    end
  end

  # No zap stanza required
end
