# This file was generated by GoReleaser. DO NOT EDIT.
cask "gh-attach" do
  name "gh-attach"
  desc "GitHub user attachment upload CLI for gh"
  homepage "https://github.com/sudosubin/gh-attach"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gh-attach"

  on_macos do
    on_intel do
      url "https://github.com/sudosubin/gh-attach/releases/download/v#{version}/gh-attach_#{version}_darwin_amd64.tar.gz"
      sha256 "aefc1fb871bb287ace4bb367b854a0e1fc3edd033908a3770811493b30076fa1"
    end
    on_arm do
      url "https://github.com/sudosubin/gh-attach/releases/download/v#{version}/gh-attach_#{version}_darwin_arm64.tar.gz"
      sha256 "c98c4932f2dd7ba3a2364130d80b41f92bc8b161897bd80babc00f4ccc361483"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sudosubin/gh-attach/releases/download/v#{version}/gh-attach_#{version}_linux_amd64.tar.gz"
      sha256 "edcecb812320cb1988069bbb8a8e313402506e0fe7ee1e277fecaaf5044f401a"
    end
    on_arm do
      url "https://github.com/sudosubin/gh-attach/releases/download/v#{version}/gh-attach_#{version}_linux_arm64.tar.gz"
      sha256 "10157f05e5ba8a8334718e6f785f97253845fb61b1b14938929da8b1e735dab2"
    end
  end

  # No zap stanza required
end
